version: '3.7'

services:
  ejemx_prod_db:
    build:
      context: ../../../
      dockerfile: ./Dockerfile.mysql
    container_name: ejemx_prod_db
    env_file: .env.dev
    volumes:
      - /var/lib/mysql/ejemx-prod-docker:/var/lib/mysql
    networks:
      ejemx_prod_net:
        ipv4_address: 10.28.0.5

  ejemx_prod_web:
    build:
      context: ../../../
      dockerfile: ./Dockerfile.php
    container_name: ejemx_prod_web
    depends_on:
      - ejemx_prod_db
    networks:
      ejemx_prod_net:
        ipv4_address: 10.28.0.6

  eje_prod_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ejemx_prod_phpmyadmin
    env_file: .env.dev.phpmyadmin
    networks:
      ejemx_prod_net:
        ipv4_address: 10.28.0.7

networks:
  ejemx_prod_net:
    name: ejemx_prod_net
    ipam:
      driver: default
      config:
        - subnet: 10.28.0.0/29

